#!/usr/bin/env bash

set -euo pipefail

active_log() {
  echo "$("$0" data_dir)/active.log"
}

data_dir() {
  local -r default_data_dir="${XDG_DATA_HOME:-${HOME}/.local/share}/git-events"
  local data_dir="${RUN_BASE_DIR:-${default_data_dir}}"
  data_dir="$(realpath "${data_dir}")"; readonly data_dir

  >&2 mkdir -p "${data_dir}"
  echo "${data_dir}"
}

"$@"
