#!/usr/bin/env bash

set -euo pipefail

readonly tsv_log="$1"

# Check if there's even anything in it
if [ ! -s "${tsv_log}" ]; then
  >&2 echo "empty file ${tsv_log} -- doing nothing"
  rm -f "${tsv_log}"
  exit 1
fi

# ---

readonly sqlite_filepath_template="$(gec_path_data_dir)/_outbox/dbs/git-events-XXXXXXXX.db"
>&2 mkdir -p "$(dirname "${sqlite_filepath_template}")"
readonly sqlite_filepath="$(mktemp "${sqlite_filepath_template}")"

git_events_collector mvp "${tsv_log}" "${sqlite_filepath}"
rm -f "${tsv_log}"
