#!/usr/bin/env bash

set -euo pipefail

default_data_dir="${XDG_DATA_HOME:-${HOME}/.local/share}/git-events"
data_dir="${RUN_BASE_DIR:-${default_data_dir}}"
readonly data_dir="$(realpath "${data_dir}")"
>&2 mkdir -p "${data_dir}"

echo "${data_dir}"
