# Warning: this is a generated file; please avoid editing it manually unless
# doing so temporarily.

jobs:
  build-git_events_collector:
    runs-on:
      - macos-latest
    steps:
      - uses: "actions/checkout@v2"
        with: {}
      - id: cache-choosenim
        name: Cache choosenim
        uses: "actions/cache@v1"
        with:
          key: "${{ runner.os }}-choosenim"
          path: "~/.choosenim"
      - id: cache-nimble
        name: Cache nimble
        uses: "actions/cache@v1"
        with:
          key: "${{ runner.os }}-nimble"
          path: "~/.nimble"
      - uses: "jiro4989/setup-nim-action@v1.2.3"
        with:
          nim-version: '1.4.2'
      - run: nimble --stacktrace:on --linetrace:on  build --accept git_events_collector
  check-shell:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
        with: {}
      - uses: "awseward/gh-actions-shell@0.1.0"
        with: {}
name: CI
on:
  - push
