# Warning: this is a generated file; please avoid editing it manually unless
# doing so temporarily.

jobs:
  - release-client:
      runs-on:
        - macos-latest
      steps:
        - uses: "actions/checkout@v2"
        - run: "echo 'TODO: plan'"
        - run: "echo 'TODO: nim setup'"
        - run: "echo 'TODO: tarball'"
        - run: "echo 'TODO: checksum'"
        - run: "echo 'TODO: create Relase'"
        - run: "echo 'TODO: upload tarball'"
        - run: "echo 'TODO: mislav/bump-homebrew-formula-action@v1.6'"
name: Release
on:
  push:
    tags:
      - "*"
