# Warning: this is a generated file; please avoid editing it manually unless
# doing so temporarily.

jobs:
  - release-client:
      runs-on:
        - macos-latest
      steps:
        - uses: "actions/checkout@v2"
        - id: plan
          run: "echo 'TODO: plan'"
        - run: "echo 'TODO: nim setup'"
        - run: "echo 'TODO: tarball'"
        - run: "echo 'TODO: checksum'"
        - env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          id: create_release
          uses: "actions/create-release@v1"
          with:
            body: "Checksum: `${{ steps.checksum.outputs.tarball_checksum }}`"
            draft: 'false'
            prerelease: 'false'
            release_name: "${{ steps.plan.outputs.git_tag }}"
            tag_name: "${{ steps.plan.outputs.git_tag }}"
        - env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          id: upload_tarball
          uses: "actions/upload-release-asset@v1"
          with:
            body: "Checksum: `${{ steps.checksum.outputs.tarball_checksum }}`"
            draft: 'false'
            prerelease: 'false'
            release_name: "${{ steps.plan.outputs.git_tag }}"
            tag_name: "${{ steps.plan.outputs.git_tag }}"
        - env:
            COMMITTER_TOKEN: "${{ secrets.COMMITTER_TOKEN }}"
          uses: "mislav/bump-homebrew-formula-action@v1.6"
          with:
            base-branch: master
            commit-message: |
              {{formulaName}} {{version}}
              
              Sourced from ${{ steps.create_release.outputs.html_url }}.
            download-url: "${{ steps.upload_tarball.outputs.browser_download_url }}"
            formula-name: git_events_collector
            homebrew-tap: awseward/homebrew-tap
name: Release
on:
  push:
    tags:
      - "*"
